bridge:
  db:
    host: localhost
    port: 3306
    username: root
    pw: 5211
    database: bridge_application
  nacos:
    addr: localhost:8848
  sentinel:
    addr: localhost:8090
  mq:
    host: localhost
    port: 5672
    virtual: /
    username: guest
    pw: guest