server:
  port: 8082
spring:
  application:
    name: project-service
#  datasource:
#    url: jdbc:mysql://mysql:3306/bridge_project?useUnicode=true&characterEncoding=UTF-8&autoReconnect=true&serverTimezone=UTC
#    username: root
#    password: 5211
#    driver-class-name: com.mysql.cj.jdbc.Driver
  data:
    mongodb:
      uri: mongodb://mongodb:27017/bridge_project
    redis:
      host: redis
      port: 6379
  cloud:
    nacos:
      discovery:
        server-addr: nacos:8848
  elasticsearch:
    uris: http://elasticsearch:9200
    username: elastic
    password: G7v*0k-JzbOKc6j3df0W
  rabbitmq:
    host: rabbitmq
    port: 5672
    virtual-host: /
    username: guest
    password: guest
    listener:
      simple:
        prefetch: 1
        acknowledge-mode: auto
        retry:
          enabled: true
mybatis-plus:
  configuration:
    default-enum-type-handler: com.baomidou.mybatisplus.core.handlers.MybatisEnumTypeHandler
  global-config:
    db-config:
      update-strategy: not_null
      id-type: auto
