bridge:
  mongodb:
    host: localhost
    port: 27017
    database: bridge_project
  redis:
    host: localhost
    port: 6379
  es:
    host: localhost
    port: 9200
    username: elastic
    pw: G7v*0k-JzbOKc6j3df0W
  nacos:
    addr: localhost:8848
  mq:
    host: localhost
    port: 5672
    virtual: /
    username: guest
    pw: guest