server:
  port: 8084
spring:
  application:
    name: notification-service
  profiles:
    active: local
  datasource:
    url: jdbc:mysql://${bridge.mysql.host}:${bridge.mysql.port}/${bridge.mysql.database}?useUnicode=true&characterEncoding=UTF-8&autoReconnect=true&serverTimezone=UTC
    username: ${bridge.mysql.username}
    password: ${bridge.mysql.pw}
    driver-class-name: com.mysql.cj.jdbc.Driver
  cloud:
    nacos:
      discovery:
        server-addr: ${bridge.nacos.addr}
  rabbitmq:
    host: ${bridge.mq.host}
    port: ${bridge.mq.port}
    virtual-host: ${bridge.mq.virtual}
    username: ${bridge.mq.username}
    password: ${bridge.mq.pw}
    listener:
      simple:
        prefetch: 1
        acknowledge-mode: auto
        retry:
          enabled: true
mybatis-plus:
  configuration:
    default-enum-type-handler: com.baomidou.mybatisplus.core.handlers.MybatisEnumTypeHandler
  global-config:
    db-config:
      update-strategy: not_null
      id-type: auto