server:
  port: 8081
spring:
  application:
    name: user-service
  profiles:
    active: local
  datasource:
    url: jdbc:mysql://${bridge.db.host}:${bridge.db.port}/${bridge.db.database}?useUnicode=true&characterEncoding=UTF-8&autoReconnect=true&serverTimezone=UTC
    username: ${bridge.db.username}
    password: ${bridge.db.pw}
    driver-class-name: com.mysql.cj.jdbc.Driver
  cloud:
    nacos:
      discovery:
        server-addr: ${bridge.nacos.addr}
  rabbitmq:
    host: ${bridge.mq.host}
    port: ${bridge.mq.port}
    virtual-host: ${bridge.mq.virtual}
    username: ${bridge.mq.username}
    password: ${bridge.mq.pw}
    connection-timeout: 1s
    template:
      retry:
        enabled: true
        initial-interval: 1000ms
        multiplier: 1
        max-attempts: 3
mybatis-plus:
  configuration:
    default-enum-type-handler: com.baomidou.mybatisplus.core.handlers.MybatisEnumTypeHandler
  global-config:
    db-config:
      update-strategy: not_null
      id-type: assign_uuid
  type-handlers-package: com.steam.user