server:
  port: 8080

spring:
  application:
    name: bridge-gateway
  cloud:
    nacos:
      discovery:
        server-addr: nacos:8848
    gateway:
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins: "http://localhost:3000"
            allowedMethods:
              - GET
              - POST
              - PUT
              - DELETE
              - OPTIONS
            allowedHeaders: "*"
            allowCredentials: true
      routes:
        - id: project-service
          uri: lb://project-service
          predicates:
            - Path=/project/**
        - id: user-service
          uri: lb://user-service
          predicates:
            - Path=/user/**,/admin/**,/company/**,/professional/**
        - id: application-service
          uri: lb://application-service
          predicates:
            - Path=/application/**
        - id: notification-service
          uri: lb://notification-service
          predicates:
            - Path=/notification/**
        - id: notification-websocket-service
          uri: lb://notification-service
          predicates:
            - Path=/ws/**
bridge:
  auth:
    excludePaths:
      - /user/login
      - /user/register
      - /ws/**
      - /user/reset
      - /notification
